version: "2"
services:
    nginx:
        container_name: h_ng
        build: nginx_container/
        ports:
         - 80:80
        volumes:
          - ./:/app
        working_dir: /app
    mysql:
        container_name: h_db
        image: mariadb
        volumes:
          - ./:/app
          - dbdata:/var/lib/mysql
        ports:
         - 9306:3306
        environment:
          - MYSQL_DATABASE=nextinterfaces_db
          - MYSQL_ROOT_PASSWORD=r0000t
        working_dir: /app
volumes:
    dbdata:
